squid_project_general_homepage:
    pattern:  /
    defaults: { _controller: SquidProjectGeneralBundle:General:accueil }

squid_project_general_homepage2:
    pattern:  /accueil
    defaults: { _controller: SquidProjectGeneralBundle:General:accueil }





squid_project_general_source:
    pattern:  /source
    defaults: { _controller: SquidProjectGeneralBundle:Source:sourceAccueil }

squid_project_general_source_new:
    pattern:  /source/new
    defaults: { _controller: SquidProjectGeneralBundle:Source:sourceNew}

squid_project_general_source_newIP:
    pattern:  /source/newIP
    defaults: { _controller: SquidProjectGeneralBundle:Source:sourceNewIP}

squid_project_general_source_all:
    pattern:  /source/all
    defaults: { _controller: SquidProjectGeneralBundle:Source:sourceAll}

squid_project_general_source_delete:
    pattern:  /source/delete/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Source:sourceDelete, id:0}

squid_project_general_source_update:
    pattern:  /source/update/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Source:sourceUpdate, id:0}





squid_project_general_destination:
    pattern:  /destination
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destAccueil }

squid_project_general_destination_all:
    pattern:  /destination/all
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destAll }

squid_project_general_destination_new:
    pattern:  /destination/new
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destNew }

squid_project_general_destination_new_DB:
    pattern:  /destination/new/DB
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destNewDB }

squid_project_general_destination_whitelist:
    pattern:  /destination/whitelist
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destWl }

squid_project_general_destination_blacklist:
    pattern:  /destination/blacklist
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destBl }

squid_project_general_destination_update:
    pattern:  /destination/update/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destUpdate, id:0}

squid_project_general_destination_delete:
    pattern:  /destination/delete/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destDelete, id:0}

squid_project_general_destination_DB_update:
    pattern:  /destination/DB/update/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destDBup}

squid_project_general_destination_DB_content:
    pattern:  /destination/DB/content/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destDBcontent}

squid_project_general_domaine_delete:
    pattern:  /destination/DB/{idDB}/domaine/delete/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destDBdomaineDel}

squid_project_general_domaine_add:
    pattern:  /destination/DB/{idDB}/domaine/add
    defaults: { _controller: SquidProjectGeneralBundle:Destination:destDBdomaineAdd}





squid_project_general_acl:
    pattern:  /acl
    defaults: { _controller: SquidProjectGeneralBundle:Acl:aclAccueil }

squid_project_general_acl_new:
    pattern:  /acl/new
    defaults: { _controller: SquidProjectGeneralBundle:Acl:aclNew }

squid_project_general_acl_all:
    pattern:  /acl/all
    defaults: { _controller: SquidProjectGeneralBundle:Acl:aclAll }

squid_project_general_acl_delete:
    pattern:  /acl/delete/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Acl:aclDelete,id:0 }

squid_project_general_acl_update:
    pattern:  /acl/update/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Acl:aclUpdate, id:0}







squid_project_general_horaire:
    pattern:  /horaire
    defaults: { _controller: SquidProjectGeneralBundle:Horaire:horaireAccueil }

squid_project_general_horaire_all:
    pattern:  /horaire/all
    defaults: { _controller: SquidProjectGeneralBundle:Horaire:horaireAll }

squid_project_general_horaire_new:
    pattern:  /horaire/new
    defaults: { _controller: SquidProjectGeneralBundle:Horaire:horaireNew }

squid_project_general_horaire_delete:
    pattern:  /horaire/delete/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Horaire:horaireDelete}




squid_project_general_restriction:
    pattern:  /restriction
    defaults: { _controller: SquidProjectGeneralBundle:Restriction:restAccueil }

squid_project_general_restriction_new:
    pattern:  /restriction/new
    defaults: { _controller: SquidProjectGeneralBundle:Restriction:restNew }

squid_project_general_restriction_all:
    pattern:  /restriction/all
    defaults: { _controller: SquidProjectGeneralBundle:Restriction:restAll }

squid_project_general_restriction_delete:
    pattern:  /restriction/delete/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Restriction:restDelete}

squid_project_general_restriction_toggle:
    pattern:  /restriction/toggle/{id}
    defaults: { _controller: SquidProjectGeneralBundle:Restriction:restToggle}



squid_project_general_MAS:
    pattern:  /miseajour
    defaults: { _controller: SquidProjectGeneralBundle:SG:mas}




squid_project_general_config:
    pattern:  /configuration
    defaults: { _controller: SquidProjectGeneralBundle:Config:accueil}

squid_project_general_config_new:
    pattern:  /configuration/new
    defaults: { _controller: SquidProjectGeneralBundle:Config:new}

squid_project_general_config_update:
    pattern:  /configuration/update
    defaults: { _controller: SquidProjectGeneralBundle:Config:update}




squid_project_general_validate:
    pattern:  /validate
    defaults: { _controller: SquidProjectGeneralBundle:Validation:validate}

squid_project_general_validate_ip:
    pattern:  /validate/ip/{ip}
    defaults: { _controller: SquidProjectGeneralBundle:Validation:validateIP}

squid_project_general_validate_source:
    pattern:  /validate/source/{src}
    defaults: { _controller: SquidProjectGeneralBundle:Validation:validateSource}

squid_project_general_validate_destination:
    pattern:  /validate/destination/{dest}
    defaults: { _controller: SquidProjectGeneralBundle:Validation:validateDestination}

squid_project_general_validate_destinationDB:
    pattern:  /validate/destinationDB/{destDB}
    defaults: { _controller: SquidProjectGeneralBundle:Validation:validateDestinationDB}

squid_project_general_validate_acl:
    pattern:  /validate/acl/{acl}
    defaults: { _controller: SquidProjectGeneralBundle:Validation:validateAcl}

squid_project_general_validate_aclSource:
    pattern:  /validate/aclSource/{src}
    defaults: { _controller: SquidProjectGeneralBundle:Validation:validateAclSource}

squid_project_general_validate_horaire:
    pattern:  /validate/horaire/{h}
    defaults: { _controller: SquidProjectGeneralBundle:Validation:validateHoraire}






squid_project_general_test:
    pattern:  /test
    defaults: { _controller: SquidProjectGeneralBundle:Restriction:test}













